version: "2"
run:
  go: "1.25"
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - staticcheck
        path: integration_test\.go
        text: 'SA1019:'
      - linters:
          - staticcheck
        path: featureset/date-range-histogram\.go
        text: 'SA9003:'
      - linters:
          - staticcheck
        path: featureset/dynamic-filter\.go
        text: 'SA9003:'
      - linters:
          - staticcheck
        path: featureset/sorting\.go
        text: 'SA9003:'
      - linters:
          - unused
        path: featureset/date-histogram\.go
        text: field `query` is unused
      - linters:
          - unused
        path: builder_test\.go
        text: func `termsAggregationToMap` is unused
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
