on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

name: SAST

env:
  GO_VERSION: 1.19.1
  GOVULNCHECK_VERSION: latest
  NANCY_VERSION: 1.0.39

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go build -v .

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go test -race -cover -v ./...

  vet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go vet ./...
  
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
  
  deps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: |
        go install golang.org/x/vuln/cmd/govulncheck@${{ env.GOVULNCHECK_VERSION }}
        
        curl -L https://github.com/sonatype-nexus-community/nancy/releases/download/v${{ env.NANCY_VERSION }}/nancy-v${{ env.NANCY_VERSION }}-linux-amd64 -o $(go env GOPATH)/bin/nancy
        chmod +x $(go env GOPATH)/bin/nancy
    
    - run: |
        govulncheck ./...
        go list -m all | nancy sleuth
